theme: jekyll-theme-tactile
title: Distort Project Homepage
description: Anonymous and Confidential messaging on the public Internet.

# Added to all absolute links as a prefix. href="/foo.css" becomes href="{baseurl}/foo.csss
# leave to empty string because we're running from the root of the repo.
# baseurl: /distortapp.org
